openapi: 3.0.2
info:
  title: election night results - data
  version: 1.0.0
  description: the uploading of the election night results data
  contact: {}
paths:
  /foobar:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/foobar'
        '401':
          description: Unauthorized
      operationId: get-foobar
      description: get a list of foobars
    post:
      summary: ''
      operationId: post-foobar
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/foobar'
              examples:
                foobar created:
                  value:
                    id: 1
                    foo: barrrrrrs
      description: create a foobar
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/foobar'
            examples:
              'foobar post ':
                value:
                  foo: barrrrrrs
        description: 'the foobar you want to make '
  '/foobar/{fooId}':
    parameters:
      - schema:
          type: string
        name: fooId
        in: path
        required: true
        description: the foobar ID
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/foobar'
              examples:
                foobar with id 1:
                  value:
                    id: 1
                    foo: barrrrrrs
        '404':
          description: Not Found
      operationId: get-foobar-fooId
      description: Get a particular foobar
      parameters: []
components:
  schemas:
    foobar:
      title: foobar
      type: object
      x-examples:
        foobar examle:
          foo: bar
      description: Simple foobar
      properties:
        id:
          type: string
        foo:
          type: string
          description: this is the foo
      required:
        - foo
      x-tags:
        - foobar
servers:
  - url: 'https://stoplight.io/p/mocks/12241/70151'
    description: stoplight mock server
