openapi: 3.0.2
info:
  title: election night results - data
  version: 1.0.0
  description: the uploading of the election night results data
  contact: {}
paths: {}
components:
  schemas: {}
servers:
  - url: 'https://stoplight.io/p/mocks/12241/70151'
    description: stoplight mock server
